public class Filter {
	 
	   private static String[] keywords = {"developer",
	    		"software development",
	    		"software engineering",
	    		"software engineer",
	    		"programmer",
	    		"software architect",
	    		"software architecture",
	    		"software testing",
	    		"software tester",
	    		"java",
	    		"game developer",
	    		"usability engineer",
	    		"ux designer",
	    		"software project manager",
	    		"c++",
	    		"c#",
	    		"Ruby on Rails",
	    		"Software project manager",
	    		"PHP",
	    		"Web developer",
	    		"App developer",
	    		"Application Support Analyst",
	    		" Applications Engineer",
	    		"Associate Developer",
	    		"Chief Information Officer",
	    		"Chief Technology Officer",
	    		"Cloud Architect",
	    		"Cloud Consultant",
	    		"Cloud Product and Project Manager",
	    		"Cloud Services Developer",
	    		"Cloud Software and Network Engineer",
	    		"Cloud System Administrator",
	    		"Cloud System Engineer",
	    		"Computer and Information Research Scientist",
	    		"Computer and Information Systems Manager",
	    		"Computer Network Architect",
	    		"Computer Programmer",
	    		"Computer Systems Analyst",
	    		"Computer Systems Manager",
	    		"Customer Support Administrator",
	    		"Customer Support Specialist",
	    		"Data Center Support Specialist",
	    		"Data Quality Manager",
	    		"Database Administrator",
	    		"Desktop Support Manager",
	    		"Desktop Support Specialist",
	    		"Director of Technology",
	    		"Front End Developer",
	    		"Help Desk Specialist",
	    		"Help Desk Technician",
	    		"IT Analyst",
	    		"IT Coordinator",
	    		"IT Director",
	    		"IT Manager",
	    		"IT Support",
	    		"IT Systems Administrator",
	    		"Java Developer",
	    		"Junior Software Engineer",
	    		"Management Information Systems Director",
	    		".NET Developer",
	    		"Network Administrator",
	    		"Network Architect",
	    		"Network and Computer Systems Administrator",
	    		"Network Engineer",
	    		"Network Systems Administrator",
	    		"Programmer Analyst",
	    		"Senior Applications Engineer",
	    		"Senior Database Administrator",
	    		"Senior Network Architect",
	    		"Senior Network Engineer",
	    		"Senior Network System Administrator",
	    		"Senior Programmer",
	    		"Senior Programmer Analyst",
	    		"Senior Security Specialist",
	    		"Senior Software Engineer",
	    		"Senior Support Specialist",
	    		"Senior System Administrator",
	    		"Senior System Analyst",
	    		"Senior System Architect",
	    		"Senior System Designer",
	    		"Senior Systems Analyst",
	    		"Senior Systems Software Engineer",
	    		"Senior Web Administrator",
	    		"Senior Web Developer",
	    		"Software Architect",
	    		"Software Developer",
	    		"Software Engineer",
	    		"Software Quality Assurance Analyst",
	    		"Support Specialist",
	    		"System Architect",
	    		"Systems Administrator",
	    		"Systems Analyst",
	    		"Systems Designer",
	    		"Systems Software Engineer​",
	    		"Technical Operations Officer",
	    		"Technical Specialist",
	    		"Technical Support Engineer",
	    		"Technical Support Specialist",
	    		"Telecommunications Specialist",
	    		"Web Administrator",
	    		"Webmaster"
	};
	   

	   public static boolean containsKeywords(Tweet currentTweet){
		   
		    String userbio = currentTweet.getUserbio();
		   
		    if (TweetStreamer.stringContainsKeyword(userbio, keywords)) {
		    	return true;		
		    }
		    
		    return false;
	   }
}
