
public class Filter {
	 
	   private static String[] keywords = {"adware",
       		
       		"alpha test",
       		"application software",
       		"coding",
       		"compiler",
       		"computer architecture",
       		"computer program",
       		"computer programming",
       		"counterprogramming",
       		"custom software",
       		"debug",
       		"debugger",
       		"design software",
       		"developer",
       		"implementation",
       		"information system",
       		"learn computer language",
       		"learn program",
       		"learn program language",
       		"metaprogram",
       		"metaprogramming",
       		"microprocessor",
       		"parser",
       		"preprogram",
       		"processor",
       		"programmable",
       		"programming language",
       		"proprogrammer",
       		"pseudocode",
       		"software bug",
       		"software development process",
       		"software documentation",
       		"software engineer",
       		"software engineering",
       		"software framework",
       		"software maintenance",
       		"software product",
       		"software release",
       		"software release life cycle",
       		"software testing",
       		"source code",
       		"subprogram",
       		"teleprogrammed",
       		"teleprogramming",
       		"waterfall model",
       		"write code",
       		"algol",
       		"antivirus",
       		"appender",       		
       		"assembler",
       		"bloatware",
       		"british computer society",
       		"certified software development professional",
       		"cobol",
       		"computer science",
       		"crossgrade",
       		"cybernetic",
       		"downloader",
       		"encode",
       		"firmware",
       		"fortran",
       		"groupware",
       		"hackathon",
       		"intranet",
       		"microcomputer",
       		"minicomputer",
       		"modularity",
       		"motherboard",
       		"multinetwork",
       		"multiprogramming",
       		"nonprogramming",
       		"optimizer",
       		"portability",
       		"programmer",
       		"shareware",
       		"softmodem",
       		"software engineering institute",
       		"swebok",
       		"techie",
       		"teletype",
       		"telnet",
       		"uploader",
       		"virtualize",
       		"wardialer"
	};
	   
	   public static boolean containsKeywords(Tweet currentTweet){
		   
		    String content = currentTweet.getContent();
		   
		    if (TweetStreamer.stringContainsKeyword(content, keywords)) {
		    	return true;		
		    }
		    
		    return false;
	   }
}
